# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7LXkFx0Nk6sAerZ5CFt1fWxeEyuCsqF
"""

!pip install openai anthropic
!pip install groq

import ipywidgets as widgets
from IPython.display import display, Markdown
import os
import requests
from openai import OpenAI
import anthropic
from google.colab import userdata # Import userdata to access Colab secrets
import google.genai as genai # Updated import for Google Gemini
from groq import Groq # Import for Groq API

# ---------------------------------------------------------
# 1. CONFIGURATION DES CLÉS API
# ---------------------------------------------------------
# 💡 ASTUCE COLAB : Utilise le panneau "Secrets" (l'icône de clé à gauche)
# pour stocker tes clés en toute sécurité au lieu de les écrire en clair ici.

# Récupération des clés API depuis les secrets Colab
os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
os.environ["ANTHROPIC_API_KEY"] = userdata.get("ANTHROPIC_API_KEY")
os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY") # New for Gemini
os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")     # New for Groq

# Configure Google Generative AI (removed genai.configure call)
# genai.configure(api_key=os.environ.get("GOOGLE_API_KEY")) # This line caused the error

# ---------------------------------------------------------
# 2. CRÉATION DES WIDGETS (L'INTERFACE)
# ---------------------------------------------------------
provider_dropdown = widgets.Dropdown(
    options=[
        'OpenAI (GPT-4o-mini)',
        'Anthropic (Claude 3.5 Sonnet)',
        'Google (Gemini 1.5 Pro)', # Added Gemini
        'Groq (Llama3-8b-8192)',   # Added Groq
        'Local (Ollama - Llama3)'
    ],
    value='OpenAI (GPT-4o-mini)',
    description='Modèle:',
)

prompt_input = widgets.Textarea(
    value='',
    placeholder='Pose ta question au LLM ici...',
    description='Message:',
    layout=widgets.Layout(width='80%', height='100px')
)

submit_button = widgets.Button(
    description='Envoyer',
    button_style='success', # Donne une couleur verte au bouton
    icon='paper-plane'
)

# Zone où la réponse s'affichera
output_area = widgets.Output()

# ---------------------------------------------------------
# 3. LOGIQUE D'APPEL DES LLMs
# ---------------------------------------------------------
def on_submit(b):
    with output_area:
        # On nettoie l'affichage précédent
        output_area.clear_output()
        print("⏳ Génération en cours, merci de patienter...")

        provider = provider_dropdown.value
        prompt = prompt_input.value

        if not prompt.strip():
            print("❌ Le message est vide. Veuillez écrire quelque chose.")
            return

        try:
            result = ""
            # --- OPENAI ---
            if 'OpenAI' in provider:
                client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
                response = client.chat.completions.create(
                    model="gpt-4o-mini", # Parfait pour des tests rapides
                    messages=[{"role": "user", "content": prompt}]
                )
                result = response.choices[0].message.content

            # --- ANTHROPIC ---
            elif 'Anthropic' in provider:
                client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
                message = client.messages.create(
                    model="claude-3-5-sonnet-20240620",
                    max_tokens=1024,
                    messages=[{"role": "user", "content": prompt}]
                )
                result = message.content[0].text

            # --- GOOGLE GEMINI ---
            elif 'Google' in provider:
                model = genai.GenerativeModel('gemini-1.5-pro', api_key=os.environ.get("GOOGLE_API_KEY")) # Pass API key directly
                response = model.generate_content(prompt)
                result = response.text

            # --- GROQ ---
            elif 'Groq' in provider:
                client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
                chat_completion = client.chat.completions.create(
                    messages=[
                        {
                            "role": "user",
                            "content": prompt,
                        }
                    ],
                    model="llama3-8b-8192", # Using a fast Groq model
                )
                result = chat_completion.choices[0].message.content

            # --- LOCAL (OLLAMA) ---
            elif 'Local' in provider:
                url = "http://localhost:11434/api/generate"
                payload = {
                    "model": "llama3",
                    "prompt": prompt,
                    "stream": False
                }
                response = requests.post(url, json=payload)
                if response.status_code == 200:
                    result = response.json().get("response", "")
                else:
                    result = f"❌ Erreur avec le modèle local. (Ollama tourne-t-il bien à l'adresse {url} ?)"

            # --- AFFICHAGE DU RÉSULTAT ---
            output_area.clear_output()
            display(Markdown(f"### Réponse de {provider}\n{result}"))

        except Exception as e:
            output_area.clear_output()
            print(f"❌ Une erreur technique s'est produite : {e}\n(Vérifiez que vos clés API sont bien configurées)")

# ---------------------------------------------------------
# 4. EXÉCUTION
# ---------------------------------------------------------
# On connecte le clic du bouton à la fonction de génération
submit_button.on_click(on_submit)

# On affiche tous les éléments à l'écran
display(provider_dropdown, prompt_input, submit_button, output_area)